defaults: &defaults
  S3_KEY: <%= ENV.fetch('S3_KEY', "AKIAJB7Z3FGKOUXPZ7ZQ") %>
  S3_SECRET: <%= ENV.fetch('S3_SECRET', "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") %>
  S3_INBOUND_BUCKET: <%= ENV.fetch('S3_INBOUND_BUCKET', "/voyzes-uploads") %>
  S3_OUTBOUND_BUCKET: <%= ENV.fetch('S3_INBOUND_BUCKET', "/voyzes-private") %>
  # S3_KEY: <%= ENV.fetch('S3_KEY', "AKIAJD2UYCYLZ3WKESBA") %>
  # S3_SECRET: <%= ENV.fetch('S3_SECRET', "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") %>
  # S3_INBOUND_BUCKET: <%= ENV.fetch('S3_INBOUND_BUCKET', "/drivethrough") %>
  EXPIRE_TIME: 300 # 5 minutes
  S3_URL: 'http://s3.amazonaws.com'  

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults